### ISSUE TITLE
Stop playing firing animation when ADSing

### ISSUE THREAD

**Issue by Albanight** [timmybo5/simple-weapon-base#10]
Playing the fire animation while aiming with certain weapons make the gun flail about making it impossible to aim properly.

**Comment by timmybo5** [comment]
You mean like with the Deagle that during the firing animation its hard to see the target?

**Comment by Albanight** [comment]
Like with pretty much all weapons. When you fire while ADSing the gun doesnt sit still enough for you to be accurate

**Comment by timmybo5** [comment]
That can be solved with individual aim down sight fire animations, I'll add support for it!

**Comment by Albanight** [comment]
Epic
