### ISSUE TITLE
what a mistake

### ISSUE THREAD

**Issue by pashaa812** [timmybo5/simple-weapon-base#100]
he following errors were found when trying to load the project: 

'ExampleGame': cannot derive from static class 'GameManager'
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\ExampleGame.cs:6

The type or namespace name 'BaseNetworkable' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\swb_base\AmmoTypes.cs:6

The type or namespace name 'AnimatedEntity' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\swb_player\PlayerBase.Base.cs:12

The type or namespace name 'IClient' could not be found (are you missing a using directive or an assembly reference?)
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\ExampleGame.cs:18

The type name 'ServerAttribute' does not exist in the type 'ConCmd'
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\ExampleCommands.cs:7

The type name 'Server' does not exist in the type 'ConCmd'
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\ExampleCommands.cs:7

The type name 'ServerAttribute' does not exist in the type 'ConCmd'
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\swb_base\Commands.cs:6

The type name 'Server' does not exist in the type 'ConCmd'
D:\SteamLibrary\steamapps\common\sbox\samples\simple-weapon-base-7.0.0\code\swb_base\Commands.cs:6

**Comment by timmybo5** [comment]
Hey! The public version is not supported for the Scene System but I am reworking it as we speak, you can access the new scene supported version here: https://github.com/timmybo5/simple-weapon-base/tree/scene-system

**Comment by pashaa812** [comment]
Thank you
