### ISSUE TITLE
Customization toggle in the WeaponSettings component doesn't actually disable customization

### ISSUE THREAD

**Issue by TheSmallBlue** [timmybo5/simple-weapon-base#105]
What the title says! Here's a video:

https://github.com/user-attachments/assets/5d1a4768-0002-4cbc-88b2-060be8efbdcd

Auto Reload does work as intended, this is a problem only with the customization option.

**Comment by TheSmallBlue** [comment]
Looking through the code this might be because the public variable "Customization" in WeaponSettings is just. Never used. At all.
The fix should be as simply as adding this to the Customization if statement in Weapon's OnUpdate method:
![Code_eAJFyP3Vtr](https://github.com/user-attachments/assets/bc20b9bc-27cc-4667-a182-c86d27fd7ad9)

**Comment by timmybo5** [comment]
Great catch! I must have added that option and forgot to implement it, will fix this week.

**Comment by timmybo5** [comment]
Fix has been pushed :D
