### ISSUE TITLE
Disabling customizations with WeaponSettings.Instance.Customization = false; doesnt turn off the key ui

### ISSUE THREAD

**Issue by SebbeJohansson** [timmybo5/simple-weapon-base#109]
Hi! Related to #105, if I disable customizations via `WeaponSettings.Instance.Customization = false;` during for example game load, the UI is still shown. The customization feature is properly disabled, but the UI key element is still present.

![image](https://github.com/user-attachments/assets/9b8c6f14-8f63-44ea-9c89-cb6862ba994c)

I have verified that it behaves the same in a "clean" project as in my version with changes.
I will look at making a PR.

**Comment by timmybo5** [comment]
Added a comment to your PR, if you fix that we can merge it :D

**Comment by timmybo5** [comment]
On this PR https://github.com/timmybo5/simple-weapon-base/pull/110

**Comment by SebbeJohansson** [comment]
@timmybo5 i dont see any comments there.
![image](https://github.com/user-attachments/assets/c91d0d89-7ab4-4f3e-925d-335669f9c895)
![image](https://github.com/user-attachments/assets/c636f2c5-02e3-4726-8331-de125b729288)

**Comment by timmybo5** [comment]
Looks like I forgot to finish the pr review, it should be visible now :)

**Comment by SebbeJohansson** [comment]
Now! Yes!

Good suggestion. fixed it.

**Comment by timmybo5** [comment]
Approved and merged, thanks!
