### ISSUE TITLE
Melee weapons when?

### ISSUE THREAD

**Issue by SebbeJohansson** [timmybo5/simple-weapon-base#111]
Hi! When is it planned to get working on melee weapons? 🗡️ 
I need it for a project where I'm using swb.

**Comment by timmybo5** [comment]
I'm not sure, there are a few projects I have to work on at the same time so it's difficult to set dates on features. I would say September/October, currently focusing on fixing all the possible errors.

**Comment by SebbeJohansson** [comment]
@timmybo5 thanks for the insight! Feel free to close.
