### ISSUE TITLE
SWB provides too much in `swb_base`

### ISSUE THREAD

**Issue by mzegar** [timmybo5/simple-weapon-base#12]
There are probably more examples of this in the codebase, but my general issue is that it feels like `SWB` provides more than just a "weapons base" inside of `swb_base`, here are a few examples...

1. Why are we setting the controller, model, camera, etc. inside of `PlayerBase.Respawn()`
2. Why is a ragdoll being created on death in `PlayerBase.OnKilled()`
3. Why is a default UI being included inside of `swb_base`
4. Deathmatch elements also included (but this is mentioned in the readme)

These are a few examples, but, I personally feel that `swb_base` should ONLY provide weapon implementation.

Extra features should be included in their own folder, such as `swb_ui`.

Thanks!

**Comment by timmybo5** [comment]
These are all just temporary as proper addon support is lacking, I def do not want to keep all that extra functionality in the base. As soon as we have proper addon support I will extract it from the base.

**Comment by mzegar** [comment]
Makes sense, hmm yeah seems like waiting for proper addon support is a good call. If you want to move it into a different namespace & folder it might make it easier to extract later.

**Comment by mzegar** [comment]
This might help you out down the line, this is the process I need to do each time I update `SWB`.

1. Drag in all folders
2. Inside `code` folder only install `swb_base`
3. Delete `deathmatch_dep`
4. Delete `InventoryBase`
5. Inside `PlayerBase` comment out `Constructor` `Respawn` `OnKilled` `TookDamage` `ShowHitmarker`
6. Inside `WeaponBase.UI` comment out `CreateHudElements` and `UISimulate`

**Comment by timmybo5** [comment]
I've extracted all the non-crucial stuff to the ExampleX classes, I've also moved deathmatch_dep outside of the swb_base folder. I also made everything left in PlayerBase overridable, left some stuff that made sense and I did not want to extend everything on base Player class as I felt that would be too intrusive.
