### ISSUE TITLE
`InfiniteAmmoType` is unclear and potentially buggy

### ISSUE THREAD

**Issue by mzegar** [timmybo5/simple-weapon-base#13]
`InfiniteAmmoType` isn't very clear with what it exactly does.

Does "normal" mean that it behaves like a normal gun? or does it behave like a normal infinite gun? Similarly, `clip` and `reserve` don't have any comments, nor really describe what they end up doing. Maybe we should have some comments for each enum, or maybe rename the enums to something more descriptive.

I also wanted to mention that if you set a gun to `InfiniteAmmoType.normal` you can reload over and over again without the ammo reserve decreasing (I'm not sure if this is intentional or not).

Thanks

**Comment by timmybo5** [comment]
Good idea, I added it in the very beginning and it def deserves some more clarity.
