### ISSUE TITLE
FAL model has incorrect position

### ISSUE THREAD

**Issue by mzegar** [timmybo5/simple-weapon-base#15]
Hey, I think the model for the FAL has incorrect modeldoc centering?

![image](https://user-images.githubusercontent.com/32153021/150698638-d00a28de-3af7-4b25-a8db-43d148f8e0e6.png)

All of the other weapons are fine, but, FAL ends up in this position when you kill another player, or you spawn it in.

Thanks.

**Comment by timmybo5** [comment]
Strange, when I drop the weapon it works fine, I'll take a look

**Comment by mzegar** [comment]
yeah, dropping seems to be fine. The FAL bugs out if you spawn it in as an ent through hammer, or sometimes when you kill a player.

**Comment by timmybo5** [comment]
Can't seem to replicate the FAL being stuck in the ground if I die, any tricks to make it happen more often?

**Comment by mzegar** [comment]
Hmm, if it isn't related to the default position in Hammer, it might be just an engine limitation. In `SWB` I was able to throw the `FAL` through the floor by crouching, looking down, and dropping it.

**Comment by timmybo5** [comment]
@mzegar Were you able to mess around with the model yet?

**Comment by mzegar** [comment]
No luck even with the fixe Fal. Also no longer using the base modelsz so up to you if you want to close this.

**Comment by timmybo5** [comment]
I'll go ahead and closed it for now then
