### ISSUE TITLE
Error creating particle while using `Laser` attachment

### ISSUE THREAD

**Issue by mzegar** [timmybo5/simple-weapon-base#21]
![image](https://user-images.githubusercontent.com/32153021/152110515-57f7149d-f657-4da4-a529-20507a0d7ef1.png)

Don't know any repo steps, experienced this during a playtest. 

This is how the UMP45 code looked like https://github.com/mzegar/sbox-TTT/blob/main/code/items/weapons/UMP45Prototype.cs

**Comment by timmybo5** [comment]
Fixed
