### ISSUE TITLE
Not an issue but how do you make animations and particles?

### ISSUE THREAD

**Issue by CodeNameBhop** [timmybo5/simple-weapon-base#22]
I would like a documentation for Simple Weapon Base since im planning on using it for a gamemode game but i dont really know how to use it yet? The main issue im struggling with is Animations and Particles, everything else is all good. I just don't know how to play back the animations and edit particle locations and stuff.

Anything would be helpful

**Comment by CodeNameBhop** [comment]
Just a matter of getting reload animations and draw, idle, fire, no empty reload and reload with a clip and particle locations on the gun and stuff.

**Comment by timmybo5** [comment]
Awesome! I plan to create a wiki page to make it easier to use/modify SWB, however in the meantime if you are wondering about how to make weapons for SWB you can follow my guide here (keep in mind they removed source importing, so you'll have to use blender/3dsmax to export models to source 2): https://wiki.facepunch.com/sbox/Importing_Source_Weapons

**Comment by CodeNameBhop** [comment]
Nice! i used blender to import source models than export to an smd or fbx, and that wiki page sounds pretty cool! I also was not aware you could import source 1 models but removing that might have been for the better.
