### ISSUE TITLE
Missing weapons when dropped

### ISSUE THREAD

**Issue by MNOGOZNAAL** [timmybo5/simple-weapon-base#24]
If you throw away your weapons. And if you try to pick it up, sometimes you will be given ammo instead of the weapon itself. 
This happens if you drop a weapon and press the drop button while picking it up.
![image](https://user-images.githubusercontent.com/38400600/154249824-0773a8de-1bff-4883-8967-2a7cfff85954.png)

**Comment by timmybo5** [comment]
Fixed!
