### ISSUE TITLE
Third Person Camera

### ISSUE THREAD

**Issue by MNOGOZNAAL** [timmybo5/simple-weapon-base#26]
If you start playing and click third person, everything will be fine. But as soon as you die and try to turn on the third person camera again, the character will begin to move very strangely. I think it's a visual bug. (Try pressing crtl)

**Comment by timmybo5** [comment]
Strange, I'll take a look :)

**Comment by MNOGOZNAAL** [comment]
i can record a video

**Comment by timmybo5** [comment]
Please do, I cannot reproduce this at all

**Comment by MNOGOZNAAL** [comment]
https://youtu.be/sipsmIP03XQ

**Comment by MNOGOZNAAL** [comment]
> Please do, I cannot reproduce this at all

https://youtu.be/sipsmIP03XQ

**Comment by timmybo5** [comment]
I'm pretty sure that's just a sandbox bug since you're not holding any weapons that could interfere with this

**Comment by MNOGOZNAAL** [comment]
> I'm pretty sure that's just a sandbox bug since you're not holding any weapons that could interfere with this

It also works on Sandbox

**Comment by timmybo5** [comment]
Open up an issue here then: https://github.com/Facepunch/sbox-issues/issues
