### ISSUE TITLE
Shotgun Broken

### ISSUE THREAD

**Issue by ndo360** [timmybo5/simple-weapon-base#3]
Currently the shotgun does the animation for reloading a single shell and pauses. The count does not increase either and the shotgun remains stuck in this manner.

I am unsure if this is due to the base, or how the weapon is programmed, but this makes shotguns unusable.

Hopefully this can be fixed soon! Love your work.

**Comment by timmybo5** [comment]
Strange, must have broken due to a recent sbox update...
Glad you love the base, more updates coming soon!

**Comment by timmybo5** [comment]
Problem solved! I will be making a new release candidate shortly.
