### ISSUE TITLE
Asset integration

### ISSUE THREAD

**Issue by timmybo5** [timmybo5/simple-weapon-base#33]
Research how weapons could be turned into assets and what structural changes that requires.

**Comment by timmybo5** [comment]
Putting on pause, asset system is lacking and would clutter base.

**Comment by Andiq** [comment]
Could you use entity prefabs?

**Comment by timmybo5** [comment]
Haven't looked into entity prefabs yet, not sure how beneficial it would be to use them. 
If you have a good idea, let me know!

**Comment by timmybo5** [comment]
Will be used with scene rework.
