### ISSUE TITLE
Block being able to throw the weapon to the ground

### ISSUE THREAD

**Issue by JMorell** [timmybo5/simple-weapon-base#4]
I want to create a weapon that is arms and I don't want them to be able to be thrown to the ground or be lost, and I haven't found a way to do it with this project.

Nice work.

**Comment by timmybo5** [comment]
Can't believe I didn't think of a way to disable dropping yet, will be added! Glad you like the base :)

**Comment by timmybo5** [comment]
Fixed in the latest commit!

**Comment by JMorell** [comment]
Thanks!
