### ISSUE TITLE
Stucking still works

### ISSUE THREAD

**Issue by MNOGOZNAAL** [timmybo5/simple-weapon-base#45]
"Fix stucking on curbs/steps" did not help. You freeze in the air and can not move.
![image](https://user-images.githubusercontent.com/38400600/190989365-914e3137-7844-4509-ac60-df842246233b.png)

**Comment by timmybo5** [comment]
Strange, It works perfectly in all my gamemodes now, will do some more testing today

**Comment by timmybo5** [comment]
Just retested a few maps, no issues found. Make sure you are not overwriting any crucial PlayerController code, will close for now.
