### ISSUE TITLE
Errors since last update

### ISSUE THREAD

**Issue by JMorell** [timmybo5/simple-weapon-base#5]
Hi, yesterday I was working on my gamemode and the weapons were working perfectly, but today I found that they were not, something must have changed at facepunch because the sandbox mode weapons are working.

https://ezshare.it/s8AvNmUWtf.mp4

Regards

**Comment by Ludendorff** [comment]
Having the same issue.

**Comment by timmybo5** [comment]
How strange, taking a look atm!

**Comment by timmybo5** [comment]
Fixed! Turned out to be caused by the new component update.
