### ISSUE TITLE
Powerups

### ISSUE THREAD

**Issue by SplatzyXD** [timmybo5/simple-weapon-base#84]
So COD Zombies powerups would be sick for a viable zombies game on s&box
some kinda base for it so it can be setup to someones liking

**Comment by SplatzyXD** [comment]
fuck i meant to add sum

**Comment by SplatzyXD** [comment]
So COD Zombies powerups would be sick for a viable zombies game on s&box
some kinda base for it

**Comment by timmybo5** [comment]
I agree that zombies is a sick gamemode, but this is not the place to ask for any zombie fundamentals. 
The weapons already support stat modifiers that the attachments are using, this could easily be used by powerups/upgrades
