### ISSUE TITLE
New s&box updates break SWB

### ISSUE THREAD

**Issue by Loganthegamer12678** [timmybo5/simple-weapon-base#99]
I DON'T GET IT! I tried reinstalling, and it still fucking fails!

**Comment by Loganthegamer12678** [comment]
Compiling ALWAYS FAIL

**Comment by timmybo5** [comment]
SWB is working for me in all my projects, what error do you get?

**Comment by Loganthegamer12678** [comment]
LOTS of errors!! (One week late BUT STILL!!!)

**Comment by Loganthegamer12678** [comment]
NVM, fresh reinstall after deleting everything....
